### ISSUE TITLE
Add GPX Export

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/directions-api-java-client#13]
Not sure if I missed it, but I think the client misses a GPX-Export function.

[Here](https://github.com/graphhopper/directions-api-java-client/blob/master/client/src/main/java/com/graphhopper/api/GraphHopperWeb.java#L159) we allways parse the result as JSON. I think we should add the GPX Export function to Api Client.

**Comment by karussell** [comment]
But how should this look like? Just saving the stream as file?

**Comment by boldtrn** [comment]
I could think of two possibilites:
- Just provide the file content as a String
- Provide a Java File object (maybe as a temporary File)

**Comment by boldtrn** [comment]
Fixed with https://github.com/graphhopper/directions-api-java-client/commit/b5f37302b888cb3e95e3eee60807e2953838782e
