### ISSUE TITLE
Finish Instruction does not contain text

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/directions-api-java-client#15]
When receiving a response we are parsing the instructions. The text of the instruction can be read with the `getName` method. However, this does not work for the `FinishInstruction`.

Here we are parsing the FinishInstruction: https://github.com/graphhopper/directions-api-java-client/blob/master/client/src/main/java/com/graphhopper/api/GraphHopperWeb.java#L304

I think we should add the text to the finish instruction as well, to have the instruction translated.

See the constructor of the FinishInstruction: https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/util/FinishInstruction.java#L27

**Comment by karussell** [comment]
You mean a custom message for the finish instructions? The default should be tr("finish"), see [here](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/util/FinishInstruction.java#L47)

**Comment by boldtrn** [comment]
> You mean a custom message for the finish instructions?

Exactly

> The default should be tr("finish")

Yes, but for the client we should not force a Translation Map to be available, especially since the instructions are already translated in the text. Translating them twice would not be a good solution IMHO.

**Comment by boldtrn** [comment]
For example:

```
instructions: [
{
distance: 173289.435,
sign: 0,
interval: [
0,
24
],
text: "Continue onto Gdynia-Karlskrona",
time: 51986830
},
{
distance: 482.378,
sign: 0,
interval: [
24,
47
],
text: "Continue",
time: 21704
},
{
distance: 306.094,
sign: -1,
interval: [
47,
54
],
text: "Turn slight left onto Kontenerowa",
time: 19375
},
....
{
distance: 0,
sign: 4,
interval: [
13544,
13544
],
text: "Finish!",
time: 0
}
```

**Comment by karussell** [comment]
Ah, okay. I see what you mean
