### ISSUE TITLE
Directions API Java Client GraphHopper dependency

### ISSUE THREAD

**Issue by devemux86** [graphhopper/directions-api-java-client#19]
@karussell the GraphHopper dependency [here](https://github.com/graphhopper/directions-api-java-client/blob/master/client/pom.xml#L27) shouldn't be `graphhopper-core`?

**Comment by karussell** [comment]
Indeed - thanks for the hint!

**Comment by boldtrn** [comment]
I recently had a some sort of related issue here. The graphhopper-core dependency is not resolvable. I had to add:

```
<repositories>
        <repository>
            <id>sonatype-oss-public</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
```

Should we add this by default for our snapshot releases?

**Comment by devemux86** [comment]
I think the artifact's name was wrong, not its location.
You probably used the old artifact from Sonatype(?).

For artifacts location we should permit also the local `.m2` repository to work.

**Comment by karussell** [comment]
> The graphhopper-core dependency is not resolvable

Indeed this is currently only on sonatype for the latest GH master

> For artifacts location we should permit also the local .m2 repository to work.

Isn't this the default for maven?

**Comment by boldtrn** [comment]
> You probably used the old artifact from Sonatype(?).

I just checked out this repository and tried to build it with maven. In the pom.xml there is dependeny `graphhopper-core`, but I cannot find it in the official maven repository. But it's in the Sonatype Repo here: https://oss.sonatype.org/content/groups/public/com/graphhopper/graphhopper-core/, so I added the repo. Tests succeed now, however I seem to be unable to find the CannotFindPoint exception I committed to GH-core some time ago. I wanted to add it to GraphHopperWeb.

**Comment by karussell** [comment]
> but I cannot find it in the official maven repository.

They do not contain snapshot releases, and we did the switch in latest master

> however I seem to be unable to find the CannotFindPoint exception I committed to GH-core some time ago. 

That is not strange, as something (again :( ) went wrong with the deployment for the snapshots

**Comment by karussell** [comment]
Ok. We removed the deprecated sonatype parent dependency and other changes were necessary due to that leading to some configuration issue, which is now fixed and should now deploy after every change again.

**Comment by boldtrn** [comment]
> We removed the deprecated sonatype parent dependency and other changes were necessary due to that leading to some configuration issue, which is now fixed and should now deploy after every change again.

Ok, so what should I do now?  Should I keep the Sonatype repository in my pom?

**Comment by karussell** [comment]
Yes, and provide this as a PR :) ?

**Comment by boldtrn** [comment]
> Yes, and provide this as a PR :) ?

see #21  ;)
