### ISSUE TITLE
Class.forName("sun.security.ssl.SSLContextImpl") not found

### ISSUE THREAD

**Issue by kchvilyov** [graphhopper/directions-api-java-client#27]
Why Class.forName("sun.security.ssl.SSLContextImpl") has not found here?
`Class<?> sslContextClass = Class.forName("sun.security.ssl.SSLContextImpl");`
Result message:
```
ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/].[ProxyServlet]] (http-localhost-127.0.0.1-8080-4) Servlet.service() for servlet ProxyServlet threw exception: java.lang.IllegalStateException: Unable to extract the trust manager on okhttp3.internal.Platform@67ec7968, sslSocketFactory is class sun.security.ssl.SSLSocketFactoryImpl
	at okhttp3.OkHttpClient.<init>(OkHttpClient.java:187) [okhttp-3.2.0.jar:]
	at okhttp3.OkHttpClient.<init>(OkHttpClient.java:60) [okhttp-3.2.0.jar:]
	at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:718) [okhttp-3.2.0.jar:]
	at com.graphhopper.api.GraphHopperWeb.<init>(GraphHopperWeb.java:66) [directions-api-java-client-0.7.0.1.jar:]
	at com.graphhopper.api.GraphHopperWeb.<init>(GraphHopperWeb.java:58) [directions-api-java-client-0.7.0.1.jar:]
```
From the code:
`final GraphHopperWeb gh = new GraphHopperWeb();`

Server: JBoss AS 7.1.1.Final "Brontes"

pom.xml:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>routeplanner2</groupId>
  <artifactId>routeplanner2</artifactId>
  <packaging>war</packaging>
  <version>2.0</version>
  <name>routeplanner2</name>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.6</maven.compiler.source>
    <maven.compiler.target>1.6</maven.compiler.target>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.jboss.spec</groupId>
      <artifactId>jboss-javaee-6.0</artifactId>
      <version>1.0.0.Final</version>
      <type>pom</type>
      <scope>provided</scope>
    </dependency>
		<dependency>
			<groupId>com.googlecode.objectify</groupId>
			<artifactId>objectify</artifactId>
			<version>5.1.10</version>
		</dependency>
		<dependency>
			<groupId>com.google.appengine</groupId>
			<artifactId>appengine-api-1.0-sdk</artifactId>
			<version>1.8.9</version>
		</dependency>
		<!-- GraphHopper -->
        <dependency>
            <groupId>com.graphhopper</groupId>
            <!-- artifactId>graphhopper-core</artifactId>
            <version>0.8-SNAPSHOT</version -->
            <artifactId>graphhopper</artifactId>
            <version>0.7.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.xmlgraphics</groupId>
                    <artifactId>xmlgraphics-commons</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
        	<groupId>com.graphhopper</groupId>
        	<artifactId>directions-api-java-client</artifactId>
        	<version>0.7.0.1</version>
       	</dependency>   
  </dependencies>
  <profiles>
    <profile>
     <id>openshift</id>
     <build>
        <finalName>routeplanner2</finalName>
        <plugins>
          <plugin>
            <artifactId>maven-war-plugin</artifactId>
            <version>2.1.1</version>
            <configuration>
              <outputDirectory>deployments</outputDirectory>
              <warName>ROOT</warName>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
```

**Comment by karussell** [comment]
Are you using this for server side or Android? And which java version?

**Comment by kchvilyov** [comment]
Thank you quick answer.
I do not use Android, it is Java ee 6 web application. I started it two ways with the same result: 
1. Locally with JBoss AS 7.1.1.Final server.
2. At remote openshift cloud with JBoss AS 7.1 Cartridge.
I have tried with graphhopper-core 0.8-SNAPSHOT and graphhopper 0.7.0 versions.

**Comment by karussell** [comment]
I have no experience with Java EE but we target Java 1.7 here, (and even 1.8 for web) so this might be the issue, not sure.

You can try 0.6.0 and a previous version of this client as they target 1.5

**Comment by kchvilyov** [comment]
I have tried with graphhopper 0.6.0 version.
The same error.

**Comment by karussell** [comment]
@kchvilyov as you've also found https://github.com/square/okhttp/issues/2323 :) ... please kind you try if version 3.4.1 for okhttp fixes your issue?

**Comment by karussell** [comment]
With >=3.3 you are able to specify Trust Manager manually rather than relying on reflection

**Comment by kchvilyov** [comment]
Thank you.
Can you describe how can I try if the latest version 3.4.1 for okhttp?
Or how to specify Trust Manager manually?

**Comment by karussell** [comment]
> Can you describe how can I use the latest version 3.4.1 for okhttp?

In your pom you can exclude okhttp from graphhopper client and include it explicitly as dependency.

> Or how to specify Trust Manager manually?

I do not know the details, just read about it

**Comment by karussell** [comment]
I've updated okhttp in the latest master which you can use via 0.8-SNAPSHOT (not recommended as SNAPSHOT versions can break at any time, but for testing if it works it is good enough)

**Comment by kchvilyov** [comment]
Thank you. the latest version 3.4.1 for okhttp fixed this issue. I used those dependencies:
`        <dependency>
            <groupId>com.graphhopper</groupId>
           <artifactId>graphhopper</artifactId>
            <version>0.7.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.xmlgraphics</groupId>
                    <artifactId>xmlgraphics-commons</artifactId>
                </exclusion>
                <exclusion>
		        	<groupId>com.squareup.okhttp3</groupId>
		        	<artifactId>okhttp</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
        	<groupId>com.squareup.okhttp3</groupId>
        	<artifactId>okhttp</artifactId>
        	<version>3.4.1</version>
       	</dependency>`

**Comment by karussell** [comment]
Perfect - thanks for the update. Did you need to customize okhttp or just use this snippet?

**Comment by kchvilyov** [comment]
I just used okhttp 3.4.1

**Comment by karussell** [comment]
Then I think we can close here.
