### ISSUE TITLE
Geocoding pom.xml needs parent ref

### ISSUE THREAD

**Issue by karussell** [graphhopper/directions-api-java-client#28]
We need to point from the geocoding pom to the parent pom to use the same deploy config etc

**Comment by karussell** [comment]
Done, but ugly when automated updated. @boldtrn do you have an idea? Probably the best would be a big unified swagger spec :)

**Comment by boldtrn** [comment]
Yes generating the whole api client using swagger would probably be the best. AFAIK he swagger codegen does not support that, but it's open source, so we could implement that or at least create an issue for that [here](https://github.com/swagger-api/swagger-codegen)?

**Comment by karussell** [comment]
I think this is no really issue for them, so I wouldn't post it there and we keep it for now as it is (and remember resetting the pom snippet after an automated update). And try to create one swagger spec for all APIs -> see new issue
