### ISSUE TITLE
Create unified swagger spec

### ISSUE THREAD

**Issue by karussell** [graphhopper/directions-api-java-client#33]
Currently we have a spec for the Geocoding and Route Optimization API but the other 4 APIs are missing. Also one spec would make something like #28 easier.

The Routing API is a bit of a problem as we have encoded points there but we can just use 'string' and for our official clients do the conversation manually in the hope that some hooks are provided from swagger.

**Comment by karussell** [comment]
This is now mainly done here: https://github.com/boldtrn/graphhopper-routing-api-swagger but will keep it open until we have moved everything into one repository and have feedback from users etc

**Comment by boldtrn** [comment]
I think we can close now?

**Comment by karussell** [comment]
Yes, this is now in the `client` module
