### ISSUE TITLE
Make timeout dynamically configurable 

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/directions-api-java-client#36]
Currently the [GraphHopperWeb implementation](https://github.com/graphhopper/directions-api-java-client/blob/master/client/src/main/java/com/graphhopper/api/GraphHopperWeb.java#L71) has a fixed timeout of 5 seconds.

5 seconds are fine when executing a CH routing request. However, a non ch routing request might take longer. Or if having a bad internet connection one might want to increase the timeout as well.

Therefore I think, it would be great to be able change the timeout on a per method basis. Currently, this would be possible with[ setting a new instance](https://github.com/graphhopper/directions-api-java-client/blob/master/client/src/main/java/com/graphhopper/api/GraphHopperWeb.java#L96) of the OKHttpClient before the request.

WDYT?

**Comment by karussell** [comment]
Why would we need to change this on a per-request basis? Because of non-CH vs. CH?

**Comment by karussell** [comment]
Then maybe we provide the timeout via the hints like we do with the service_url in the matrix client: https://github.com/graphhopper/directions-api-java-client/blob/master/client/src/main/java/com/graphhopper/api/GHMatrixAbstractRequester.java#L167

**Comment by boldtrn** [comment]
> Why would we need to change this on a per-request basis? Because of non-CH vs. CH?

Yes, that would be one example. Think of every request that might take longer than 5 seconds. For example using the client in Android. When having a bad connection, requests might take longer than 5 seconds, just to transfer the data.

> Then maybe we provide the timeout via the hints like we do with the service_url in the matrix client

Exactly, that's how I would solve it.

**Comment by devemux86** [comment]
@karussell's idea is nice, flexibility per request via the hints seems fine, for not having to set global large timeouts for all API.

Like @boldtrn mentioned, tests showed that very long non-CH routes can often lead to fail because of response's time being larger than default timeout.
