### ISSUE TITLE
Filter by OSM fields e.g. Type

### ISSUE THREAD

**Issue by webdevilopers** [graphhopper/directions-api-java-client#37]
Not sure if this is the correct repository for this issue.
I've been doing my first geocoding requests e.g. for `26655 Westerstede`.

```txt
1 => {#743 ▼
      +"osm_id": 13859067
      +"osm_type": "W"
      +"extent": array:4 [▶]
      +"country": "Deutschland"
      +"osm_key": "highway"
      +"city": "Westerstede"
      +"osm_value": "motorway_link"
      +"postcode": "26655"
      +"name": "AS Westerstede-West"
      +"state": "Niedersachsen"
      +"point": {#742 ▶}
    }
    2 => {#741 ▶}
    3 => {#739 ▼
      +"osm_id": 2095887435
      +"osm_type": "N"
      +"country": "Deutschland"
      +"osm_key": "place"
      +"city": "Westerstede"
      +"osm_value": "postcode"
      +"postcode": "26655"
      +"name": "Westerstede"
      +"state": "Niedersachsen"
      +"point": {#738 ▶}
    }
    4 => {#737 ▶}
    5 => {#735 ▼
      +"osm_id": 3379693
      +"osm_type": "R"
      +"extent": array:4 [▶]
      +"country": "Deutschland"
      +"osm_key": "place"
      +"city": "Westerstede"
      +"osm_value": "postcode"
      +"postcode": "26655"
      +"name": "Westerstede"
      +"state": "Niedersachsen"
      +"point": {#734 ▶}
    }
    6 => {#733 ▼
      +"osm_id": 1124403982
      +"osm_type": "N"
      +"country": "Deutschland"
      +"osm_key": "place"
      +"city": "Westerstede"
      +"osm_value": "postcode"
      +"postcode": "26655"
      +"name": "Westerstede"
      +"state": "Niedersachsen"
      +"point": {#732 ▶}
    }
```

The response shows a lot of extra OSM fields e.g `type`, `key` or `value` which do not seem to be mentioned in the current docs?
* https://graphhopper.com/api/1/docs/geocoding/#example-output-for-the-case-typejson
It would be nice to see them added and explained.

The OSM types are liste here:
* http://wiki.openstreetmap.org/wiki/DE:Nominatim

>  osm_type=[N|W|R]
> osm_id=<value>
>   Angabe eines OSM-Objektes (Node, Way oder Relation, dessen Adresse gefunden werden soll.
>   Wenn möglich, dieses anstelle von Lat/Lon angeben 

Is there a possibility to filter the results by OSM fields to only return `postcodes` or `nodes` for instance?

BTW: Why are there identical "descriptions" with different IDs and `point`?
```json
      +"osm_type": "N"
      +"country": "Deutschland"
      +"osm_key": "place"
      +"city": "Westerstede"
      +"osm_value": "postcode"
```

Possibly related issues:
* https://github.com/graphhopper/directions-api-java-client/issues/26
* https://github.com/graphhopper/directions-api-java-client/pull/20

**Comment by karussell** [comment]
> The response shows a lot of extra OSM fields e.g type, key or value which do not seem to be mentioned in the current docs?

This could be. We need to update this, but still some fields can be missing as we only document what is available for all providers. At least that is the idea.

**Comment by boldtrn** [comment]
> Is there a possibility to filter the results by OSM fields to only return postcodes or nodes for instance?

I don't think so, sorry. Why would you need that? 

> Why are there identical "descriptions" with different IDs and point?

If you are searching for `Westerstede` the geocoding tries to match your search with values found in the data. Therefore the geocoding tries to provide you with the most important results for the search query. Since different use-cases are looking for different results you can pick the result that best fits your use-case. Some people are looking for places, others for streets, and so on. Therefore, the geocoding returns different types and additional information so you can pick the right data.

**Comment by webdevilopers** [comment]
I just tried to avoid manually post-filtering the results since I only need a single result for "postcode and city" @boldtrn .

Please see the example results above https://github.com/graphhopper/directions-api-java-client/issues/37#issue-199271419:
```json
      +"osm_type": "N"
      +"country": "Deutschland"
      +"osm_key": "place"
      +"city": "Westerstede"
      +"osm_value": "postcode"
```
As you can see this result exists twice vor osm type, key and value. The only difference is the point - and ID of course. How should I decide? Are there any additional parameters for the query to use?

**Comment by webdevilopers** [comment]
@karussell  wrote:
> ...but still some fields can be missing as we only document what is available for all providers.

While testing I stumbled upon a geocoding result for `2672`. The result looks like this:
```json
  +"osm_id": 1401234798
  +"osm_type": "N"
  +"country": "Russland"
  +"osm_key": "place"
  +"osm_value": "hamlet"
  +"name": "2672 км"
  +"state": "Oblast Omsk"
  +"point": {#697 ▼
    +"lng": 72.876656
    +"lat": 55.0917223
  }
```

I'm missing the `city` property here. According to the docs it should indeed be a field available for all providers, right?
* https://graphhopper.com/api/1/docs/geocoding/#example-output-for-the-case-typejson

> To try it append the parameter to the URL like &provider=nominatim, the result structure should be identical in all cases - if not, please report this back to us.
I'm using the `default` provider!

**Comment by karussell** [comment]
The problem here is that it is not really a town/city (it is a hamlet). @boldtrn should we include it as `city` (can mean also 'place') or use a different field like `place`?

**Comment by boldtrn** [comment]
@webdevilopers 

> I just tried to avoid manually post-filtering the results since I only need a single result for "postcode and city" 

In this case I would use `provider=nominatim` and check the results for the `osm_value` or the `city`. I would use the first result that has for example the city key.

@karussell 

>  should we include it as city (can mean also 'place') or use a different field like place?

I will check this, thanks.
