### ISSUE TITLE
Unify GraphHopperWeb Implementations

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/directions-api-java-client#39]
Currently, we have two separated implementations of the GraphHopperWeb class. One in the graphhopper/graphhopper repo and one in this repo. Wouldn't it be nice to reuse some of the functions or even completely reuse the one specified in graphhopper/graphhopper. Therefore we would only need to extend from this class in this repo?

What do you think? Is there a reason we haven't done this yet? Because of the dependencies of the web-module? In this case we can maybe move the GraphHopperWeb class somewhere else?

**Comment by karussell** [comment]
The dependencies you mentioned are one reason (and also Json vs. okhttp3). The other reason is that we currently have a rather "fat" client relying on GH core and I'm not sure if we should follow this route or create a "thin" client using okhttp/swagger.

**Comment by boldtrn** [comment]
Ok thanks, makes sense. Should we close here?
