### ISSUE TITLE
Make async and in-sync possible for Matrix

### ISSUE THREAD

**Issue by karussell** [graphhopper/directions-api-java-client#4]
Both request methods have its advantages and disadvantages so make them both possible.

**Comment by karussell** [comment]
Fixed via https://github.com/graphhopper/directions-api-java-client/commit/bd1c8bcfb5275fd68a8844afd41a36e208edf53c

@oblonski would you please try with the snapshot and I'll release a new version then. Batch is the default and in-sync (good only for small requests) can be done via:

`new GraphHopperMatrixWeb(new GHMatrixSyncRequester())`

**Comment by oblonski** [comment]
Both Sync and Batch mode work well. Note that it breaks code once a
custom serviceURL is set.

Am 24/06/15 um 14:01 schrieb Peter:

**Comment by karussell** [comment]
Hmmh, I could introduce another constructor with the url which by default uses async?

**Comment by oblonski** [comment]
That would work. And if we do not want this constructor in future, we
could deprecate it immediately.

Am 25/06/15 um 10:42 schrieb Peter:

**Comment by oblonski** [comment]
I can do it. Okay?

Am 25/06/15 um 10:42 schrieb Peter:

**Comment by karussell** [comment]
Already done & released. Can take a bit to appear though

**Comment by oblonski** [comment]
Great!

Am 25/06/15 um 11:24 schrieb Peter:
