### ISSUE TITLE
Geocoding: Add osm_key

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/directions-api-java-client#48]
Currently the Geocoding client does not parse the field `osm_key`.

**Comment by karussell** [comment]
I'm unsure if we should expose this as this is rather low level (it would not work for other data sources)

**Comment by devemux86** [comment]
Aren't already exposed the `osm_id` and `osm_type` which are more low level and kind of OSM specific?

**Comment by karussell** [comment]
True, yes.
